[package]
name = "structs_tuples"
version = "0.1.0"
authors = ["Smith Carvajal <36459473+hamiltonsalazar@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
